<?php
    $this->plugin('basePath')->setBasePath('/public/');
?>
<style>
    
    @font-face {
        font-family: fontlato;
        src: url(/public/fonts/lato-light.ttf);
    }
    
</style>
<div class="paginas col-lg-12" data-pagina="inicio" style="display: block;margin-top:-60px;">
    <div class="about layer">
        <div>
            <div class="social instagram">
                <a href="https://www.instagram.com/_hj_fotografia_/" target="_blank"><img src="<?= $this->basePath('img/Instagram.svg') ?>"></a>
            </div>
    <!--        <div class="social vk">
                <a href="https://vk.com/ivangorokhov" target="_blank"><img src="<?= $this->basePath('img/VK.svg') ?>"></a>
            </div>-->
            <div class="social youtube">
                <a href="https://www.youtube.com/channel/UCKvRb16gk5EeE7XYfR9u0aA" target="_blank"><img src="<?= $this->basePath('img/Youtube.svg') ?>"></a>
            </div>
            <div class="social px500">
                <a href="https://500px.com/hjfotografia" target="_blank"><img src="<?= $this->basePath('img/500px.svg') ?>"></a>
            </div>
            <div class="social facebook">
                <a href="https://www.facebook.com/hj.fotografias" target="_blank"><img src="<?= $this->basePath('img/Facebook.svg') ?>"></a>
            </div>
    <!--        <div class="social periscope">
                <a href="http://www.periscope.tv/ivan_gorokhov" target="_blank"><img src="<?= $this->basePath('img/Periscope.svg') ?>"></a>
            </div>-->
        </div>
        <div class="text" style="font-family: fontlato;" >
            <div class="HJFOTOGRAFIA">
                <img style="max-width: 65%" src="<?= $this->basePath('img/logo_drone.png') ?>" id="hjfotografia"/>
            </div>
            <!--<div class="desc">Ivan Gorokhov - Russian photographer-traveler.</div>-->
                <!--<div class="line"></div>-->
            <div class="clearfix"></div>
            <div class="desc" style="text-transform: none; text-align: justify" >A HJ Fotografia mostra quem somos de verdade com apenas um “clique”. Fotografar é arte, arte de sorrisos, de sentimentos e emoções, é a arte de ser.  Ser fotografado é ser moldado, colocar-se à disposição do que a arte pode fazer em nós.  Quer navegar nesse mundo da arte? Venha para HJ Fotografia.</div>
            <div class="text-right" style="margin-top: 10px; text-transform: none">Maria Cecília Dias Belan</div>
        </div>
    </div>
</div>