<?php
    $this->plugin('basePath')->setBasePath('/public/');
?>
<style>
    
    .sobre {
        display: none;
        margin-top:60px;
        background: white;
        min-height: 470px;
    }
    
    
</style>

<div class="paginas sobre col-lg-12" data-pagina="sobre">
    
    <div class="modal-body clearfix">
        <div class="col-lg-12">
            <span class="text-center">
                <h2><br>Sobre</h2>
            </span>
        </div>
        <div class="col-lg-12" style="margin-top:10px;">
            <div class="col-lg-4 text-center">
                <img style="width: 300px; height: 350px" src="<?= $this->basePath('img/quem_sou_eu.jpg') ?>">
            </div>
            <div class="col-lg-8 text-center">
                <span style="font-size: 20px;" class="text-justify">
                <p>Inspirado na beleza e simplicidade, o fotógrafo Hélio Júnior se dedica
                a fotografia como expressão artística e de preservação da memória, desde
                2009 começou a fotografar a beleza da natureza, o que era antes um
                hobby e diversão, se apaixonou, e hoje se tornou um grande profissional.</p><br><br>
                </span>
                <span style="font-size: 16px;">
                    Administra Sua Própria Empresa<br>
                    Áudio e Vídeo<br>
                    Iluminação e Photoshop<br>
                    Detalhista em Edição<br>
                </span>
            </div>
            
        </div>
    </div>
    
</div>