<?php
echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/'))
        ->prependStylesheet($this->basePath() . '/public/css/login.css');

$message_login = '';
if (isset($this->messageLogin)) {
    $message_login = $this->messageLogin;
}

?>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700">

        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <style>
            #user, #pass {
                text-transform: uppercase
            }

            a:link, a:hover, a:visited { color: #23527c; }
        </style>
    </head>
    <body>
        <div class="container">

            <div id="login" style="margin: 0 auto">
                <?php if ($this->sessao()->isLogged()) : ?>
                    <span>Você está logado!</span>
                <?php else : ?>     
                    <form method="POST" id="form_login" action="/acesso/login">
                        <fieldset class="clearfix">
                            <p><span class="fa fa-user fa-2x"></span><input type="text" placeholder="Usuário" name="user" id="user" data-obrigatorio /></p> <!-- JS because of IE support; better: placeholder="Username" -->
                            <p><span class="fa fa-lock fa-2x"></span><input type="password" placeholder="Senha" name="password" id="pass" data-obrigatorio /></p> <!-- JS because of IE support; better: placeholder="Password" -->
                            <p><input type="submit" class="btn btn-primary" value="Entrar"></p>
                        </fieldset>
                    </form>
                <?php endif; ?>
            </div> <!-- end login -->
        </div>
    </body>

</html>
