<?php 
    echo $this->doctype(); 
    $this->plugin('basePath')->setBasePath('/public/');
?>

<html lang="en">
    
    
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav" id="opcao-menu">
                        <li><a class="font" href="#" data-pagina="inicio">Início</a></li>
                        <li><a class="font" href="#" data-pagina="portifolio">Portfólio</a></li>
                        <li><a class="font" href="#" data-pagina="contato">Contato</a></li>
                        <li><a class="font" href="#" data-pagina="sobre">Sobre</a></li>
                        <li><a class="font" href="#" data-pagina="depoimento">Depoimentos</a></li>
                        <li><a class="font" href="#" data-pagina="login"><i class="fa fa-lock"></i> Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="main col-lg-12">
                <?php echo $this->partial('paginas/sobre')?>
                <?php echo $this->partial('paginas/inicio')?>
                <?php echo $this->partial('paginas/contato')?>
                <?php echo $this->partial('paginas/portifolio')?>
                <?php echo $this->partial('paginas/depoimento',['depoimentos'=>$this->depoimentos])?>
                <?php echo $this->partial('paginas/login')?>
        </div>
    </body>

<script>
    
    $('#opcao-menu li a').click( function() { //ao clicar no link de menu
        
        var pagina = $(this).attr('data-pagina');
        
        $('.paginas').hide(); //oculta pagina exibida
        
        if (pagina == "portifolio") {
            $('#pagina-index').removeClass('page-inicio');
            $('#pagina-index').addClass('page-portifolio');
        } else {
            $('#pagina-index').removeClass('page-portifolio');
            $('#pagina-index').addClass('page-inicio');
        }
        
        $('div[data-pagina="'+pagina+'"]').show(); //exibe a div referente a pagina clicada
        
    });
    
</script>
